### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by kapilsharma** [phpreboot/website#123]
Need to add favicon to the site.

**Comment by aabi01** [comment]
Hi @kapilsharma 
Can i work on this issue?

**Comment by kapilsharma** [comment]
Sure @aabi01 

Github do not support uploading .ico file in issues. I'll commit ico file for favicon in code and update.

You will just need to put favicon code in master template.

Thanks,
Kapil.

**Comment by aabi01** [comment]
Yeah Sure @kapilsharma 
Let me know the name of the ico file, i will add it in the master file !

**Comment by kapilsharma** [comment]
@aabi01 

I guess adding useless icon/logo in code might not be a good idea.

Instead, I'd uploaded all PHP Reboot logos/favicon I've on google drive and made the folder public. You can download the favicon/logo form google drive and add only the one needed to git.

Google drive folder: https://drive.google.com/drive/folders/0B8KhIeQYQjwbdFh1ZWE3Yk1wQlE?usp=sharing

Please let me know if you have any doubt.

**Comment by aabi01** [comment]
Yeah sure !
