### ISSUE TITLE
Contribution page

### ISSUE THREAD

**Issue by kapilsharma** [phpreboot/website#44]
A new page with details of how anyone can contribute on PHPreboot.com website.

- In making site (Fixing issues here)
- Add/manage articles (blogs) to the magazine.

**Comment by kapilsharma** [comment]
For now, added contribution guide as github markdown and it is linked through magazine page from website.

Although we should have contribute page on phpreboot.com, this is no longer have priority. Changing priority to low.

**Comment by jottajorge** [comment]
I would like to work on the few typos issues in contribution page!
